Repository googleapis/java-networkconnectivity, pull requests merged in 2021-05, with the labels that each got.

#68 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes, context: none

#69 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: networkconnectivity, automerge, cla: yes

#70 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes, context: full

#74 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes, context: full

#75 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes, context: full

#77 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes, context: full

#79 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes, context: full
