Repository googleapis/java-networkconnectivity, pull requests merged in 2021-01, with the labels that each got.

#10 fix: resolve dependency issue
  grpc-google-cloud-networkconnectivity-v1alpha1/pom.xml
Labels: cla: yes

#11 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#9 chore: Set namespaces for C#, PHP, and Ruby
  proto-google-cloud-networkconnectivity-v1alpha1/src/main/java/com/google/cloud/networkconnectivity/v1alpha1/CommonProto.java
  proto-google-cloud-networkconnectivity-v1alpha1/src/main/java/com/google/cloud/networkconnectivity/v1alpha1/HubProto.java
  proto-google-cloud-networkconnectivity-v1alpha1/src/main/proto/google/cloud/networkconnectivity/v1alpha1/common.proto
  proto-google-cloud-networkconnectivity-v1alpha1/src/main/proto/google/cloud/networkconnectivity/v1alpha1/hub.proto
  synth.metadata
Labels: api: networkconnectivity, cla: yes, context: full

#12 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: networkconnectivity, automerge, cla: yes
